### PR TITLE
removed unused variables

### PR DESCRIPTION
**Pull request by frzifus**
reduce compiler warnings

### CODE REVIEW

**Comment by Paeti** [comment]
LGTM

**Review by Paeti — APPROVED** [review]

**Review by S1ngularity96 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by Devil123166 — APPROVED** [review]

**Review by KnutZuidema — COMMENTED** [review]
Unnecessary changes, should not be approved

**Comment by frzifus** [comment]
@KnutZuidema What's wrong with that?

**Review by mooxl — APPROVED** [review]

**Comment by MathiasKoAc** [comment]
Deep improvement (y)

**Review by juliusmh — APPROVED** [review]
LGTM 👍

**Review by diggidong — APPROVED** [review]

**Review by schogges — APPROVED** [review]

**Pull request closed without merging**
